apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp2
  name: flaskapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp2
  template:
    metadata:
      labels:
        app: flaskapp2
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: hasifzulkifli95/ttd2:latest
        name: flaskapp2
#        env:
#        - name: FLASK_APP
#          value: "app.py"
        # Change to development to enable debug mode
#        - name: FLASK_ENV
#          value: "production"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service-2
  labels:
    app: flaskapp2
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: flaskapp2
#  type: LoadBalancer
#  externalIPs:
#    - 192.168.4.106
