apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mata-lb
  name: mata-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mata-lb
  template:
    metadata:
      labels:
        app: mata-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: hasifzulkifli95/mata-lb:latest
        name: mata-lb
#        env:
#        - name: FLASK_APP
#          value: "app.py"
        # Change to development to enable debug mode
#        - name: FLASK_ENV
#          value: "production"
        ports:
        - containerPort: 80
        resources:
          requests:
#            cpu: 50m
#            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
#        readinessProbe:
#          httpGet:
#            path: /ready
#            port: 80
#          initialDelaySeconds: 15
#          periodSeconds: 5
#        livenessProbe:
#          httpGet:
#            path: /alive
#            port: 80
#          initialDelaySeconds: 20
#          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mata-lb-service
#  labels:
#    app: mata-lb-service
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: mata-lb
  type: LoadBalancer
  externalIPs:
    - 192.168.4.106
