apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: twistcode-object-detection
  name: twistcode-object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twistcode-object-detection
  template:
    metadata:
      labels:
        app: twistcode-object-detection
    spec:
      terminationGracePeriodSeconds: 240
      containers:
      - image: hasifzulkifli95/twistcode-object-detection-service:latest
        name: twistcode-object-detection
#        env:
#        - name: FLASK_APP
#          value: "app.py"
        # Change to development to enable debug mode
#        - name: FLASK_ENV
#          value: "production"
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: twistcode-object-detection-service
  labels:
    app: twistcode-object-detection
spec:
  ports:
  - port: 5002
    protocol: TCP
    name: http
    targetPort: 5002
  selector:
    app: twistcode-object-detection
#  type: LoadBalancer
#  externalIPs:
#    - 192.168.4.106
