apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: hasifzulkifli95/ttd1:latest
        name: flaskapp
#        env:
#        - name: FLASK_APP
#          value: "app.py"
        # Change to development to enable debug mode
#        - name: FLASK_ENV
#          value: "production"
        ports:
        - containerPort: 80
#        resources:
#          requests:
#            cpu: 50m
#            memory: 128Mi
#          limits:
#            cpu: 100m
#            memory: 256Mi
#        readinessProbe:
#          httpGet:
#            path: /ready
#            port: 80
#          initialDelaySeconds: 15
#          periodSeconds: 5
#        livenessProbe:
#          httpGet:
#            path: /alive
#            port: 80
#          initialDelaySeconds: 20
#          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  selector:
    app: flaskapp
  type: LoadBalancer
  externalIPs:
    - 192.168.4.106
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flaskapp-ingress
  annotations:
    # Disables http redirect to https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flaskapp
            port:
              number: 80
          #serviceName: flaskapp
          #servicePort: 80
